version: '2.3'
services:
  jenkins:
    image: joon09/jenkins-docker:1.0
    user: root
    restart: unless-stopped
    hostname: jenkins
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./jenkinsdata/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
#      - /usr/local/bin/docker-compose:/usr/bin/docker-compose
    ports:
      - 8083:8080
      - 50000:50000